In [5]:
import cv2
sift = cv2.xfeatures2d.SIFT_create()
sift.detectAndCompute?

In [4]:
cv2.BFMatcher_create?

In [1]:
import numpy as np
img= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
type(img)

numpy.ndarray

In [5]:
np.sort(img.ravel())[5]

6

In [9]:
img=img.ravel()
img.length

AttributeError: 'numpy.ndarray' object has no attribute 'length'

In [15]:
type(7>>1)

int

In [7]:
img[0:2,0:2]=np.array([[2, 2], [2, 2]])

In [8]:
img

array([[2, 2, 3],
       [2, 2, 6],
       [7, 8, 9]])

In [14]:
import numpy 
numpy.floor(7/2)

3.0

In [16]:
numpy.floor(7/2)

3.0

In [17]:
a='123'

In [18]:
a==a

True

In [19]:
a=='12'

False

In [33]:
img

array([[7, 2, 3],
       [2, 7, 6],
       [7, 8, 7]])

In [34]:
img[0:3,0:3]

array([[7, 2, 3],
       [2, 7, 6],
       [7, 8, 7]])

In [35]:
img[[np.arange(3)],[np.arange(3)]]

array([[7, 7, 7]])

In [36]:
img[(0,1,2),(0,1,2)]

array([7, 7, 7])

In [37]:
img[[0,1,2],[0,1,2]]

array([7, 7, 7])

In [43]:
img[0:3,(0,1,2)]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
type((0,1,2))

tuple

In [49]:
type([0,1])

list

In [50]:
[np.arange(3)]

[array([0, 1, 2])]

In [51]:
img[np.arange(3),np.arange(3)]

array([1, 5, 9])

In [52]:
import numpy as np

img= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
img[np.arange(3),np.arange(3)]

array([1, 5, 9])

In [53]:
img(0,0)

TypeError: 'numpy.ndarray' object is not callable

In [54]:
img = np.array([[1], [2], [3]])

In [61]:
img

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [63]:
img

matrix([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

In [64]:
type(np.array([[1], [2], [3]]))

numpy.ndarray

In [23]:
img= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
output = np.zeros_like(img)
type(output[1,1])

numpy.int32

In [28]:
np.zeros_like?

In [29]:
np.zeros?

In [69]:
img[..., 0]

array([1, 4, 7])

In [70]:
img[..., [0]]

array([[1],
       [4],
       [7]])

In [7]:
img[0,0]

1

In [20]:
import numpy as np
import numpy.matlib
import cv2
import scipy.signal as signal

img_Gray = cv2.imread('D:/Code/Test/Snorlax.jpg', 0)
cv2.imshow('img_Gray', img_Gray)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

img = img_Gray
m, n = img.shape  # 获取输入图片的尺寸（行和列）
img_Padding = np.zeros((m, n))
img_Padding[0:m, 0:n] = img
img_Padding = img
# 第二种方式就没有问题


# img_Padding=np.array(img_Padding).astype('uint8')
cv2.imshow('img_Padding', img_Padding)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()


In [20]:
img[100:105,100:105]

array([[203, 203, 203, 203, 203],
       [203, 203, 203, 203, 203],
       [203, 203, 203, 203, 203],
       [203, 203, 203, 203, 203],
       [203, 203, 203, 203, 203]], dtype=uint8)

In [21]:
img_Padding[100:105,100:105]

array([[203., 203., 203., 203., 203.],
       [203., 203., 203., 203., 203.],
       [203., 203., 203., 203., 203.],
       [203., 203., 203., 203., 203.],
       [203., 203., 203., 203., 203.]])