In [10]:
import numpy as np
? np.ndarray.argsort

In [12]:
np.random.randint?

In [16]:
a =np.random.randint(10,size = 6)

In [17]:
a

array([4, 6, 3, 8, 8, 6])

In [18]:
a < 5

array([ True, False,  True, False, False, False])

In [19]:
np.where(a <= 5)[0]

array([0, 2], dtype=int64)

In [8]:
import matplotlib.patches as patches
patches.Rectangle?

In [1]:
# 多于一个维度  
import numpy as np 
a = np.array([[1,  2],  [3,  4]])  
print (a)

[[1 2]
 [3 4]]


In [7]:
boxes = np.array([[200, 200, 400, 400, 0.99],
    [220, 220, 420, 420, 0.9],
    [100, 100, 150, 150, 0.82],
    [200, 240, 400, 440, 0.5]])
boxes

array([[200.  , 200.  , 400.  , 400.  ,   0.99],
       [220.  , 220.  , 420.  , 420.  ,   0.9 ],
       [100.  , 100.  , 150.  , 150.  ,   0.82],
       [200.  , 240.  , 400.  , 440.  ,   0.5 ]])

In [14]:
box = boxes = np.array([200, 200, 400, 400, 0.99])
box[0、3]

SyntaxError: invalid character in identifier (<ipython-input-14-52d46c300621>, line 2)